In [113]:
import gymnasium as gym
import random
import numpy as np

In [114]:
#env_name = "CartPole-v1"
#env_name = "MountainCar-v0"
env_name = "Acrobot-v1"
#env_name = "Pendulum-v1"
env = gym.make(env_name, render_mode='human')
print("Observation Space:", env.observation_space)
print("Action Space:", env.action_space)
type(env.action_space)

Observation Space: Box([ -1.        -1.        -1.        -1.       -12.566371 -28.274334], [ 1.        1.        1.        1.       12.566371 28.274334], (6,), float32)
Action Space: Discrete(3)


gymnasium.spaces.discrete.Discrete

In [115]:
class Agent():
    def __init__(self,env):
        try:
            self.action_size = env.action_space.n
            print("Action Size:", self.action_size)
        except:
            self.action_low = env.action_space.low
            self.action_high = env.action_space.high
            self.action_shapre = env.action_space.shape
        
    def get_action(self,observation):
        try:
            action = random.choice(range(self.action_size))
            print(observation)
        except:
            action = np.random.uniform(self.action_low, self.action_high, self.action_shapre)
            print(observation)
            
        #pole_angle = observation[2]
        #print(action, pole_angle)

        # if pole_angle < 0:
        #     action = 0  # Move left
        # else:
        #     action = 1  # Move right
        return action

In [116]:
agent = Agent(env)
env.reset()

for _ in range(100):
    action = agent.get_action(observation)
    observation, reward, done, truncated, info = env.step(action)
    env.render()
    if done:
        env.reset()
env.close()

Action Size: 3
[-0.9140023  -0.40570906  5.4587083 ]
[ 0.99882984  0.04836291  0.99949604 -0.03174446 -0.20324099  0.44987634]
[-0.9140023  -0.40570906  5.4587083 ]
[ 0.99882984  0.04836291  0.99949604 -0.03174446 -0.20324099  0.44987634]
[ 0.9999528  -0.00971856  0.99541867  0.09561197 -0.3616034   0.7933976 ]
[ 0.9961195  -0.08801125  0.96387875  0.2663415  -0.40077168  0.9021819 ]
[ 0.9999528  -0.00971856  0.99541867  0.09561197 -0.3616034   0.7933976 ]
[ 0.9961195  -0.08801125  0.96387875  0.2663415  -0.40077168  0.9021819 ]
[ 0.9890231  -0.14776097  0.91880053  0.3947221  -0.18634918  0.4309179 ]
[ 0.98738885 -0.15831381  0.90695167  0.42123476  0.08177674 -0.14533429]
[ 0.9890231  -0.14776097  0.91880053  0.3947221  -0.18634918  0.4309179 ]
[ 0.98738885 -0.15831381  0.90695167  0.42123476  0.08177674 -0.14533429]
[ 0.9915792  -0.12950206  0.9274103   0.3740456   0.20219088 -0.35673103]
[ 0.99760914 -0.06910864  0.9649809   0.26232025  0.389781   -0.7954147 ]
[ 0.9915792  -0.12950